### PR TITLE
Mod fixes for indicators

### LINKED ISSUE #3: Indicators only supports (main) mods
https://github.com/elpekenin/qmk_modules/blob/80f57095b99a3f6c828009b46f5491e3152fc6a7/indicators/indicators.c#L29

`get_mods()|get_oneshot_mods()` is generally better, especially since I use oneshot mods a lot. :D

### PR DESCRIPTION
**Pull request by drashna**
checks oneshot mods too, if not disabled.  ~~And swaps mods based on magic config.~~ (not now, because it only works for 5-bit packed mods)

Fixes #3

### CODE REVIEW

**Comment by drashna** [comment]
I do have a fix for the 8bit mod thing with magic, that appears to work, but not sure if it's worth putting in or not.

**Comment by elpekenin** [comment]
If it works put it in, why not?

File: indicators/indicators.c [hunk 1]
```diff
@@ -29,6 +29,10 @@ bool draw_indicators(uint8_t led_min, uint8_t led_max) {
     uint8_t mods  = get_mods();
     uint8_t layer = get_highest_layer(layer_state);
 
+#ifndef NO_ACTION_ONESHOT
+    mods |= get_oneshot_mods();
+#endif // NO_ACTION_ONESHOT
```
Comment (elpekenin) [inline indicators/indicators.c:34]: I'd rather not have the comment, since this is a one-liner and we can easily see its opening `#if`

Comment (drashna) [reply indicators/indicators.c]: Fair enough, just force of habbit for me.

**Comment by drashna** [comment]
> If it works put it in, why not?

Added. Though, I'm sure it could be written better .... but I'm not sure how.  Did test with these changes and keeps behavior consistent with expectations

**Comment by elpekenin** [comment]
>  I'm sure it could be written better .... 

Bitwise struct would be readable, but probably a bit longer, as in:
```c
typedef union {
    uint8_t raw;
    struct PACKED {
        bool left_shift: 1;
        // and so on, no idea what the order is
    } bits;
} mods_t;

mods_t orig = {.raw = get_mods()};
mods_t out = orig;
if (swap_gui_alt) {
    out.bits.gui = out.bits.alt;
    out.bits.alt = out.bits.gui;
}

// etc
```
And to be honest, i would even integrate this upstream, as it would be much friendlier for new users than fiddling with bitwise ops

**Comment by drashna** [comment]
Yeah, a struct would make things simpler, I think.   But yeah, I think this is something that should be done upstream.

**Comment by elpekenin** [comment]
Will update to `mod_t` when(if) PR gets merged upstream, tyvm
